// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdDSUhE8QYPee3UPXiiMgLV85q1wc1rTw',
    appId: '1:1031510969032:web:0e1fdf239c4ec8fa9bb3fd',
    messagingSenderId: '1031510969032',
    projectId: 'learnenglish-fbdbd',
    authDomain: 'learnenglish-fbdbd.firebaseapp.com',
    storageBucket: 'learnenglish-fbdbd.appspot.com',
    measurementId: 'G-7GJNPKJLCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGlSvUfREDn3gwTLinRqtcaQ53AGap8sQ',
    appId: '1:1031510969032:android:ded3b4977a0eb1419bb3fd',
    messagingSenderId: '1031510969032',
    projectId: 'learnenglish-fbdbd',
    storageBucket: 'learnenglish-fbdbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAosG3X4TIYbdhYm8FAvQdddF5b-VUORK8',
    appId: '1:1031510969032:ios:043de3050ef53d009bb3fd',
    messagingSenderId: '1031510969032',
    projectId: 'learnenglish-fbdbd',
    storageBucket: 'learnenglish-fbdbd.appspot.com',
    androidClientId: '1031510969032-66r5ej8bi2nd04ialr73j6bvhgrs9le3.apps.googleusercontent.com',
    iosClientId: '1031510969032-iu21194196jqr4tj0uvdvbcaolt79tsq.apps.googleusercontent.com',
    iosBundleId: 'com.example.advancedMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAosG3X4TIYbdhYm8FAvQdddF5b-VUORK8',
    appId: '1:1031510969032:ios:043de3050ef53d009bb3fd',
    messagingSenderId: '1031510969032',
    projectId: 'learnenglish-fbdbd',
    storageBucket: 'learnenglish-fbdbd.appspot.com',
    androidClientId: '1031510969032-66r5ej8bi2nd04ialr73j6bvhgrs9le3.apps.googleusercontent.com',
    iosClientId: '1031510969032-iu21194196jqr4tj0uvdvbcaolt79tsq.apps.googleusercontent.com',
    iosBundleId: 'com.example.advancedMobile',
  );
}
